workflows:
  android-workflow:
    name: Android AAB Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
